import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { ThemeModeScript } from 'flowbite-react';
import { Vazirmatn } from 'next/font/google';
const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
const vazirmatn = Vazirmatn({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <body className={vazirmatn.className}>{children}</body>
    </html>
  );
}
